### ISSUE TITLE
What it is purpose?

### ISSUE THREAD

**Issue by Dazmed707** [stevesec/stealth-gophish#1]
mod ?
what is features?

**Comment by stevesec** [comment]
1. Removed Headers from GoPhish
2. Changed the X-Mailer header to be a random 3

**Comment by Dazmed707** [comment]
Se puede implementar lo del siguiente proyecto en este repositorio
Que sea compatible con 0.12.1

https://github.com/puzzlepeaches/sneaky_gophish

https://www.sprocketsecurity.com/resources/never-had-a-bad-day-phishing-how-to-set-up-gophish-to-evade-security-controls

O ya está todo eso y algo más implementado?

**Comment by Dazmed707** [comment]
Thanks, go compile this project

New methods add future, thanks.

Eggs cleaned.

**Comment by Dazmed707** [comment]
Maybe this project can be protected, with BB?

Or would this project itself be enough?

It would be nice to have a new logo for this project and a video of installing Gophish + BB from scratch, for example BBphish or GoBBphish, similar to the combination that came out on Evilgophish.

https://github.com/D00Movenok/BounceBack

**Comment by stevesec** [comment]
Thank you for the suggestion, we typically use it with Warhorse which has NGINX as a reverse proxy:

https://github.com/warhorse/warhorse

**Comment by Dazmed707** [comment]
Yes, I was researching and reading your blog, can you help me what should I install to mainly avoid the red screen, have I researched everything that happened to you as well, or would just Warhorse be enough?

![image](https://github.com/stevesec/stealth-gophish/assets/35184132/7469adc2-ee95-48c2-a4e4-37765f522bb8)

i need a clean red team operation for phishing

**Comment by stevesec** [comment]
Warhorse would be enough as you are using a CDN that increases trust with your target (azureedge.net).

Also, would suggest using a domain from expireddomains.net that would also increase trust with your target.

**Comment by Dazmed707** [comment]
Buy domain in cloudflare not reDo you recommend buying a domain from Cloudflare?

and there would be a problem if the domain has google in its name like

google-domaintest.com
logingoogleus.com
updatepass-google.com?

or do I need a different domain without google in the name?

**Comment by stevesec** [comment]
I buy a domain wherever its cheapest (i.e., NameCheap)

Yes, anything with the target's name within the domain gets flagged.

If you have any other comments, feel free to message me on Discord, the link is on my site.

**Comment by Dazmed707** [comment]
I was trying to install it, do you have telegram or any contact so as not to overwhelm with messages here?

or some warhorse guide with evilginx, I don't quite understand what the yaml does for warhorse

**Comment by stevesec** [comment]
I would check out the warhorse documentation as unfortunately, I don't have enough time to spend with warhorse documentation (the documentation isn't as thorough as we all hoped).

**Comment by Dazmed707** [comment]
If I've already checked, I'm not getting anywhere, everything is not complete. It is not clear what else needs to be done.

**Comment by Dazmed707** [comment]
![image](https://github.com/stevesec/stealth-gophish/assets/35184132/8bbe8255-0fe7-4ecb-9907-b673083961d0)
Can you help me, I can't enter the evilginx shell, in the log I get that, but it gives me an error that it is restarting or it shows me that the phishlet has not been found, I put google.yaml in the docker_evilginx phishlet folder
