### ISSUE TITLE
Add code project modded-gophish

### ISSUE THREAD

**Issue by Dazmed707** [stevesec/stealth-gophish#2]
acaba to dirty a gophish mod limpio of evilgophish in the sponsors channel.

i have code.

<img width="951" alt="image" src="https://github.com/stevesec/stealth-gophish/assets/35184132/0a575840-0eb5-43f0-8a95-7befcd50b421">

update u project whit modded-gophish ?

**Comment by stevesec** [comment]
Let's create a separate project
